# Generated by Django 2.2.6 on 2019-10-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('about', models.CharField(max_length=200)),
                ('image', models.ImageField(max_length=1000, upload_to='')),
            ],
        ),
    ]
