# Generated by Django 2.2.6 on 2019-10-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
